name: SGS CI/CD

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]
jobs:

  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar o JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Executar Suítes de Testes (Unitários e Integração)
        run: mvn test -Dtest=AllUnitTestsSuite,AllIntegrationTestsSuite

      - name: Compilar o pacote JAR
        run: mvn clean package -DskipTests

      - name: Salvar o artefato JAR
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-app
          path: target/*.jar

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Baixar o artefato JAR
        uses: actions/download-artifact@v4
        with:
          name: spring-boot-app
          path: target/

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sgs-api:latest

      - name: Deploy na AWS EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
            
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/sgs-api:latest
            
            docker stop sgs-api || true
            docker rm sgs-api || true
            
            docker run -d \
            --name sgs-api \
            -p 8080:8080 \
            --restart always \
            -e SPRING_PROFILES_ACTIVE=prod \
            ${{ secrets.DOCKERHUB_USERNAME }}/sgs-api:latest
            
            echo "Verificando o estado do LocalTunnel no PM2..."
            
            if pm2 describe sgs-tunnel > /dev/null 2>&1; then
              echo "O sgs-tunnel já existe. Reiniciando para garantir a conectividade..."
              pm2 restart sgs-tunnel
            else
              echo "O sgs-tunnel não foi encontrado. Criando um novo processo em segundo plano..."
              pm2 start lt --name "sgs-tunnel" -- --port 8080 --local-host 127.0.0.1 --subdomain sistema-gerenciamento-solicitacao-api
            fi
            
            pm2 save